### PR TITLE
Some edits.

### PR DESCRIPTION
**Pull request by auguwu**
**Added**:
* A bit more JSDoc. (`@event DBLWebhook#<event>`)
* Used deconstruction when you defined the `http` module.

### CODE REVIEW

**Comment by auguwu** [comment]
when york-senpai ignores you for ~2 months :cry:

**Comment by rjm-codes** [comment]
@YorkAARGH

**Comment by tonkku107** [comment]
Why York?

**Comment by auguwu** [comment]
@tonkku107 didn't York own the NPM package/GitHub repository? (~~blame void~~)

**Comment by tonkku107** [comment]
for this module? lol no

**Comment by rjm-codes** [comment]
not the gh

**Comment by rjm-codes** [comment]
the repo has been a dbl thing

**Comment by rjm-codes** [comment]
pretty sure he's a, if not the, dev

**Comment by tonkku107** [comment]
what I'm super confused now

dblapi.js is and has always been originally by me

**Comment by tonkku107** [comment]
And about this PR, I'll merge it when there's some other edits for a new update

**Comment by rjm-codes** [comment]
o shit

**Pull request merged**
