### PR TITLE
chore: keep d.js client initialization up to date

### PR DESCRIPTION
**Pull request by Idris1401**

### CODE REVIEW

**Comment by Idris1401** [comment]
after thought, I think you didn't specify any lib because it can also be eris
I'll let it open because I'm not sure tho

**Review by Galkon — APPROVED** [review]

**Comment by jpbberry** [comment]
`topgg-autoposter` is purposefully library agnostic. I don't think this is a good idea as the client initialization is different across discord.js and eris for example.
```js
const Eris = require("eris");

// Replace TOKEN with your bot account's token
const bot = new Eris("Bot TOKEN", {
    intents: [
        "guildMessages"
    ]
});
```
vs
```js
const { Client, GatewayIntentBits } = require('discord.js');
const client = new Client({ intents: [GatewayIntentBits.Guilds] });
```

In a perfect world I'd not even include the initialization, I just want to make sure that the `client` variable is obvious.

**Comment by Idris1401** [comment]
then the client initialization should be fully removed imo (also the current example is for discord.js. so if you wanna keep it, it needs to be updated)

**Comment by jpbberry** [comment]
The point of it is to give an example of a client initialization, it isn't discord.js because it's not platform specific.
It's an initialization of a Discord client, both eris, djs, and others have the concept of client initialization.

**Pull request closed without merging**
