### PR TITLE
Made some stuff ez

### PR DESCRIPTION
**Pull request by archturtle**
Why tonkku just why

### CODE REVIEW

**Comment by tonkku107** [comment]
Nice joke

**Comment by archturtle** [comment]
its not a meme its real
now fix

**Comment by archturtle** [comment]
make it easier nub

**Comment by tonkku107** [comment]
what do you mean easier

**Comment by archturtle** [comment]
cleaner

**Comment by tonkku107** [comment]
Messier imo

**Comment by archturtle** [comment]
Use object destructing and become a good programmer kek

**Comment by tonkku107** [comment]
I'll use it when there's a point in using it

**Comment by archturtle** [comment]
lmao kek

**Comment by archturtle** [comment]
i see a point in using it now

**Pull request closed without merging**
