### PR TITLE
update snek

### PR DESCRIPTION
**Pull request by davidcralph**
snek is good

### CODE REVIEW

**Comment by auguwu** [comment]
no u

**Comment by tonkku107** [comment]
I'm keeping snek 3 for a while. Idk if the final release of snek 4 is compatible with node 8 now but I'd like to keep this module node 8 compatible

**Comment by davidcralph** [comment]
it is compatible

**Comment by tonkku107** [comment]
I guess I'll take a look when I'm working on the next version. Would be nice to know what's changed tho

**Pull request closed without merging**
