### PR TITLE
Replaced `client` with `api`

### PR DESCRIPTION
**Pull request by EhsanFox**
Replaced `client` with `api` since it's what it's called at the beginning (kinda dumb idk)

### CODE REVIEW

**Comment by jpbberry** [comment]
Please set these documentations inside of the JSDOC in the src/, then run `npm run build` to build the docs rather than editing the build.

**Comment by velddev** [comment]
Unrelated, but can't we move these docs to top-gg/docs?

**Comment by EhsanFox** [comment]
couldn't find the JSDOC (maybe a direct link can be useful)
also, I didn't find anything about the https://topggjs.readthedocs.io/en/latest/Api.html to edit as the same as the Api.md file that I just edited....

**Comment by jpbberry** [comment]
> Unrelated, but can't we move these docs to top-gg/docs?

Moving them would mean we would need to auto-build them, if you want that then sure, but the current jsdocs are currently just passed to https://topggjs.rtfd.io

**Comment by jpbberry** [comment]
> couldn't find the JSDOC (maybe a direct link can be useful)

https://github.com/top-gg/node-sdk/blob/master/src/structs/Api.ts#L77

**Comment by velddev** [comment]
> Moving them would mean we would need to auto-build them, if you want that then sure, but the current jsdocs are currently just passed to https://topggjs.rtfd.io

Ah I see, it's generated docs. Might be interesting to have this be done in the future @Xetera. Especially with the search bar you've added we could get a lot more docs in now :)

**Comment by EhsanFox** [comment]
> Please set these documentations inside of the JSDOC in the src/, then run `npm run build` to build the docs rather than editing the build.

I just edited the structures too ( unfortunately I can not `npm run build` at this moment! )

**Comment by EhsanFox** [comment]
i will close this pull request and u can check the other one for both edits

**Comment by EhsanFox** [comment]
https://github.com/top-gg/node-sdk/pull/52

**Pull request closed without merging**
