### PR TITLE
deps: update dependencies

### PR DESCRIPTION
**Pull request by VoltrexKeyva**
- Update several developer dependencies to their new major versions.
- Update a dependency and other developer dependencies to their latest versions.

### CODE REVIEW

**Comment by jpbberry** [comment]
Wanna put in the new release token too?

**Comment by VoltrexKeyva** [comment]
> Wanna put in the new release token too?

I wanted to do that in a different PR so the changes are in commits dedicated to them, but I can do that in this PR if you want.

**Comment by jpbberry** [comment]
up2u, it’d be best to make a release after this PR

**Comment by VoltrexKeyva** [comment]
The different PR approach sounds more cleaner so I have those changes ready for a new PR right after this, PTAL.

**Review by jpbberry — APPROVED** [review]

**Pull request merged**
