### PR TITLE
Fixed typings for event handlers on the DBLWebhook class

### PR DESCRIPTION
**Pull request by zihadmahiuddin**

### CODE REVIEW

**Comment by tonkku107** [comment]
What exactly is being "fixed" here?

**Comment by zihadmahiuddin** [comment]
When using `dblapi.js` in a TypeScript project, the typing mess things up.
With the following code, I get these errors `Property 'hostname' does not exist on type 'string'`, `Property 'port' does not exist on type 'string'` and `Property 'path' does not exist on type 'string'`.
```ts
dbl.webhook.on("ready", (hook) => {
  console.log(
    `Webhook running at https://${hook.hostname}:${hook.port}${hook.path}`
  );
});
```
This is because the typing file says that the callback function's signature should be like this:
```ts
(hostname: string, port: number, path: string) => void
```
which is not correct. The correct signature is something like this:
```ts
({hostname: string, port: number, path: string}) => void
```
Same thing for the `vote` event. I fixed the typing file so now it doesn't report any error in TypeScript projects.

**Comment by tonkku107** [comment]
Alright, looks good to me but I am not a typescript user.

**Review by tonkku107 — DISMISSED** [review]

**Comment by zihadmahiuddin** [comment]
Sorry, I forgot to sign commits last time. So I had to commit again.

**Review by tonkku107 — APPROVED** [review]

**Comment by succubus86** [comment]
You rock

**Review by succubus86 — APPROVED** [review]

**Review by succubus86 — COMMENTED** [review]
Ty

**Review by succubus86 — APPROVED** [review]

**Review by succubus86 — APPROVED** [review]

**Pull request merged**
